In [28]:
import pandas as pd

In [29]:
df = pd.read_csv("../CSV ASIGNATURAS/FÍSICA - CSV/campo_gravitatorio.csv", encoding="utf-8")
df.head()

,año,convocatoria,ejercicio,opcion,enunciado,imagen,aviso
0,2016.0,Junio,1,B,a) Defina velocidad de escape de un planeta y ...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN
1,2016.0,Junio,3,A,Dos partículas de masas m 3kg y m  5kg se en...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN
2,2016.0,Reserva 2,1,A,a) Enuncie las leyes de Kepler. b) Dos satélit...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN
3,2016.0,Reserva 2,3,B,La masa de la Tierra es aproximadamente 81 vec...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN
4,2016.0,Reserva 3,1,B,a) Explique las características del campo y de...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN

In [30]:
df[~df.aviso.isna()]

,año,convocatoria,ejercicio,opcion,enunciado,imagen,aviso
106,NaN,NaN,NaN,NaN,Considere dos masas puntuales iguales separada...,enunciados_PNG/2025 - Campo gravitatorio_png/2...,sin metadatos
118,NaN,NaN,NaN,NaN,Discuta razonadamente si los siguientes enunci...,enunciados_PNG/2025 - Campo gravitatorio_png/2...,sin metadatos
121,NaN,NaN,NaN,NaN,Razone la veracidad de las siguientes afirmaci...,enunciados_PNG/2026 - Campo gravitatorio_png/2...,sin metadatos
122,NaN,NaN,NaN,NaN,Un niño de 15 kg resbala desde el reposo a lo ...,enunciados_PNG/2026 - Campo gravitatorio_png/2...,sin metadatos

In [31]:
df["asignatura"] = "Física"
df["tema"] = "campo gravitatorio"
df = df[df.aviso.isna()]
df.año = df.año.astype(int)

In [32]:
def create_id(row):
    id_string = f"{row["año"]}_{row["convocatoria"]}"
    if not pd.isna(row["ejercicio"]):
        id_string += f"_{row["ejercicio"]}"
    if not pd.isna(row["opcion"]):
        id_string += f"_{row["opcion"]}"
    return id_string

In [33]:
df["id"] = df.apply(lambda row: create_id(row), axis = 1)
df = df[["id"] + list(df.columns[:-2])]

Limpiar línea de año y convocatoria de los enunciados.

In [34]:
import re

HEADER = re.compile(r"""
    \b(?:F[IÍ]SICA|QU[IÍ]MICA|MATEM[AÁ]TICAS)   # asignatura (con o sin tilde)
    [A-ZÁÉÍÓÚÑ\s.]*?                            # resto del nombre: II, APLICADAS A LAS CC.SS. II...
    \.\s*(?:19|20)\d{2}\.                       # año
    (?:\s*\(?[A-ZÁÉÍÓÚÑ0-9]+\b\)?\.?)*          # convocatoria, ejercicio, opción...
""", re.VERBOSE)

def quitar_cabecera(texto):
    texto = HEADER.sub(" ", texto)
    return re.sub(r"\s+", " ", texto).strip()

In [35]:
enunciado_original = df.loc[0, "enunciado"]
df["enunciado"] = df["enunciado"].apply(quitar_cabecera)

Comprobación de enunciado eliminado:

In [36]:
print(enunciado_original)

a) Defina velocidad de escape de un planeta y deduzca su expresión. b) Se coloca un satélite en órbita circular a una altura h sobre la Tierra. Deduzca las expresiones de su energía cinética mientras orbita y calcule la variación de energía potencial gravitatoria que ha sufrido respecto de la que tenía en la superficie terrestre. FISICA. 2016. JUNIO. EJERCICIO 1. OPCIÓN B

In [37]:
print(df.loc[0,"enunciado"])

a) Defina velocidad de escape de un planeta y deduzca su expresión. b) Se coloca un satélite en órbita circular a una altura h sobre la Tierra. Deduzca las expresiones de su energía cinética mientras orbita y calcule la variación de energía potencial gravitatoria que ha sufrido respecto de la que tenía en la superficie terrestre.

Insertar saltos de línea antes de cada apartado: a), b), c),...

In [38]:
def insert_new_line(statement):
    new_st = statement
    for point in ["a", "b", "c", "d"]:
        new_st = new_st.replace(f" {point})", f"\n{point})")
    return new_st

In [39]:
df["enunciado"] = df.enunciado.apply(insert_new_line)

Comprobación de enunciado eliminado:

In [40]:
print(enunciado_original)

a) Defina velocidad de escape de un planeta y deduzca su expresión. b) Se coloca un satélite en órbita circular a una altura h sobre la Tierra. Deduzca las expresiones de su energía cinética mientras orbita y calcule la variación de energía potencial gravitatoria que ha sufrido respecto de la que tenía en la superficie terrestre. FISICA. 2016. JUNIO. EJERCICIO 1. OPCIÓN B

In [41]:
print(df.loc[0,"enunciado"])

a) Defina velocidad de escape de un planeta y deduzca su expresión.
b) Se coloca un satélite en órbita circular a una altura h sobre la Tierra. Deduzca las expresiones de su energía cinética mientras orbita y calcule la variación de energía potencial gravitatoria que ha sufrido respecto de la que tenía en la superficie terrestre.

Normalizar texto:

In [42]:
import unicodedata
df.enunciado = df.enunciado.apply(lambda texto : unicodedata.normalize("NFKC", texto))

Eliminar espacios múltiples:

In [43]:
df.enunciado = df.enunciado.apply(lambda texto : re.sub(r"[ \t]+", " ", texto).strip())

In [44]:
df.head()

,id,año,convocatoria,ejercicio,opcion,enunciado,imagen,aviso,asignatura
0,2016_Junio_1_B,2016,Junio,1,B,a) Defina velocidad de escape de un planeta y ...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN,Física
1,2016_Junio_3_A,2016,Junio,3,A,Dos partículas de masas m 3kg y m  5kg se en...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN,Física
2,2016_Reserva 2_1_A,2016,Reserva 2,1,A,a) Enuncie las leyes de Kepler.\nb) Dos satéli...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN,Física
3,2016_Reserva 2_3_B,2016,Reserva 2,3,B,La masa de la Tierra es aproximadamente 81 vec...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN,Física
4,2016_Reserva 3_1_B,2016,Reserva 3,1,B,a) Explique las características del campo y de...,enunciados_PNG/2016 - Campo gravitatorio_png/2...,NaN,Física

In [45]:
df.sample(10).to_csv("sample_classification.csv", index = False, encoding="utf-8")

In [49]:
df[df.id.str.endswith("nan")]

Empty DataFrame
Columns: [id, año, convocatoria, ejercicio, opcion, enunciado, imagen, aviso, asignatura]
Index: []